version: '3'
services:
  api:
    build: .
    container_name: xxx-api
    working_dir: /var/www/app
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/app
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
